# YOLOv5 🚀 by Ultralytics, AGPL-3.0 license

# Train/val/test sets as 1) dir: path/to/imgs, 2) file: path/to/imgs.txt, or 3) list: [path/to/imgs1, path/to/imgs2, ..]
path: ../LicensePlateDataset/
train: train/images/ # dataset root dir
val: val/images/ # val images (relative to 'path') 128 images
test: test/images/
# test: # test images (optional)

# Classes
nc: 1
names:
- LicencePlate

